### PR TITLE
Eliminate warnings from test run via `pytest.ini`

### PR DESCRIPTION
**Pull request by robotAstray**
# Summary

This pull request aims to fix [issue 19](https://github.com/CQCL/pytket-qiskit/issues/19)

# Details & Comments

To fix [issue 19](https://github.com/CQCL/pytket-qiskit/issues/19) a simple modification has been made to `pytest.ini`. This modification ignores warnings when  running tests.

### CODE REVIEW

**Comment by cqc-melf** [comment]
Hi @robotAstray 
Thank you for taking a look on the issue.

I think there might be a misunderstanding.
The idea was that each of the warnings should be investigates and the cause of it should be found. If it is possible to solve the cause of the warning that should be done as well.
In cases that the warnings can't be solved within pytket-qiskit they can just stay, they are not causing a failure of the test run.

**Comment by robotAstray** [comment]
@cqc-alec I see, ok I will try to work on it!

**Comment by CalMacCQ** [comment]
I think a lot of the test warnings are due to the fact there are still some deprecatred qiskit content in the tests

**Comment by robotAstray** [comment]
@CalMacCQ @cqc-alec Good morning, I made some changes to my local repository and I will open a draft pull request shortly. I still have more changes to add.

**Pull request closed without merging**
