### PR TITLE
Add conversion of controlled unitary gates from Qiskit to TKET.

### PR DESCRIPTION
**Pull request by gkpotter**
# Description

Add support for converting controlled unitary gates from Qiskit to TKET.

# Related issues

Please mention any github issues addressed by this PR.

# Checklist

- [x] I have performed a self-review of my code.
- [x] I have commented hard-to-understand parts of my code.
- [ ] I have made corresponding changes to the public API documentation.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have updated the changelog with any user-facing changes.

# Notes

I have yet to update the changelog/API docs, in case more changes or refactoring are required.

### CODE REVIEW

**Comment by cqc-melf** [comment]
Hi @gkpotter
Thank you for the PR.
There is one issues with the format check, could you take care of this?
Besides that it is looking good.

**Comment by CalMacCQ** [comment]
I think its just a case of runnig the black formatter on the qiskit convert file

```shell
black qiskit_convert.py
```

**Comment by gkpotter** [comment]
Oops sorry about that. Just re-ran black on `qiskit_conver.py`!

**Comment by cqc-melf** [comment]
Looks good, I have run the checks locally and they all work. It would be nice to add the conversion in the other direction, too. If you don't have the time to do that, I will add an issue for that and try to do it in the near future.

If you don't want to add the other direction, please update the changelog and I am happy to approve this.

**Review by cqc-melf — COMMENTED** [review]
See comment above

**Comment by gkpotter** [comment]
I updated the changelog. Unfortunately, right now I do not have time to implement conversion in the other direction.

**Comment by CalMacCQ** [comment]
> I updated the changelog. Unfortunately, right now I do not have time to implement conversion in the other direction.

Thanks for the useful contribution @gkpotter :) This reminded me that the qiskit conversion code should be refactored.

@cqc-melf Are you fine with this being merged now?

**Comment by cqc-melf** [comment]
I have added an issue for that, https://github.com/CQCL/pytket-qiskit/issues/378

**Review by cqc-melf — APPROVED** [review]

**Comment by CalMacCQ** [comment]
@gkpotter This should now be in the [0.56](https://github.com/CQCL/pytket-qiskit/releases/tag/v0.56.0) release. Thanks again for adding this.

**Pull request merged**
