### PR TITLE
Update integration tests to replace retired backends with current ones

### LINKED ISSUE #152: Replace soon-to-be-retired IBMQ machines in tests
On or around 26 September 2023 the following quantum systems are due to be retired: `ibmq_lima`, `ibmq_belem`, `ibmq_quito`, `ibmq_manila`, `ibmq_jakarta`, `ibmq_guadalupe`.

### PR DESCRIPTION
**Pull request by cqc-alec**
Closes #152 .

Integration tests running here: https://github.com/CQCL/pytket-qiskit/actions/runs/6340224704

### CODE REVIEW

**Comment by cqc-melf** [comment]
Is the fail of the test expected?

**Comment by cqc-alec** [comment]
> Is the fail of the test expected?

It's because of a license issue: every IBMQ user has to accept a new licence agreement, including the CI user.

**Comment by cqc-melf** [comment]
Looks like there is still one test not working, are you looking into that?

**Comment by cqc-alec** [comment]
> I solved the licence issue, but looks like there is still one test not working, are you looking into that?

Thank you. I think this must be due to an API change in qiskit somewhere. Will investigate.

**Comment by cqc-alec** [comment]
I fixed this and one other error. Now all tests are passing here and [here](https://github.com/CQCL/pytket-qiskit/actions/runs/6348563024).

**Review by cqc-melf — APPROVED** [review]

**Pull request merged**
