### PR TITLE
Release/1.18

### PR DESCRIPTION
**Pull request by cqc-melf**

### CODE REVIEW

**Comment by CalMacCQ** [comment]
Should we upgrade to qiskit 0.44.0 in the new release?

**Comment by cqc-alec** [comment]
> Should we upgrade to qiskit 0.44.0 in the new release?

Yes I think so but I don't know how difficult that will be (#153 ). Can try updating the dependency on this branch but I suspect some other changes will be requires, in which case I'd probably wait as there aren't any other new features here.

**Comment by cqc-melf** [comment]
I have tried that, but it is not working. I did not wanted to delay the release because of that. I would do that next week independent of this

**Comment by cqc-melf** [comment]
And I think we still should do this release because of the changes to the documentation, which could be released

**Pull request merged**
